const CONFIRMATION_PAGE_OPENED = "CONFIRMATION_PAGE_OPENED";

const ACTION_CONFIRMATION_PAGE_OPENED = () => {
  return {
    type: CONFIRMATION_PAGE_OPENED,
  };
};

export default ACTION_CONFIRMATION_PAGE_OPENED;
