const TIME_PREFERENCE_PAGE_OPENED = "TIME_PREFERENCE_PAGE_OPENED";

const ACTION_TIME_PREFERENCE_PAGE_OPENED = () => {
  return {
    type: TIME_PREFERENCE_PAGE_OPENED,
  };
};

export default ACTION_TIME_PREFERENCE_PAGE_OPENED;
