const ADMIN_CONFIRM_NEW_PASSWORD_RESET = "ADMIN_CONFIRM_NEW_PASSWORD_RESET";

const ACTION_ADMIN_CONFIRM_NEW_PASSWORD_RESET = () => {
  return {
    type: ADMIN_CONFIRM_NEW_PASSWORD_RESET,
  };
};

export default ACTION_ADMIN_CONFIRM_NEW_PASSWORD_RESET;
