const ANY_CHEM_PEELS_LAST_MONTH_NO_RESET = "ANY_CHEM_PEELS_LAST_MONTH_NO_RESET";

const ACTION_ANY_CHEM_PEELS_LAST_MONTH_NO_RESET = () => {
  return {
    type: ANY_CHEM_PEELS_LAST_MONTH_NO_RESET
  };
};

export default ACTION_ANY_CHEM_PEELS_LAST_MONTH_NO_RESET;
