const ADD_PROFILE_PHOTO_CLICKED_RESET = "ADD_PROFILE_PHOTO_CLICKED_RESET";

const ACTION_ADD_PROFILE_PHOTO_CLICKED_RESET = () => {
  return {
    type: ADD_PROFILE_PHOTO_CLICKED_RESET,
  };
};

export default ACTION_ADD_PROFILE_PHOTO_CLICKED_RESET;
