const ADD_PROFILE_PHOTO_CLICKED = "ADD_PROFILE_PHOTO_CLICKED";

const ACTION_ADD_PROFILE_PHOTO_CLICKED = () => {
  return {
    type: ADD_PROFILE_PHOTO_CLICKED,
  };
};

export default ACTION_ADD_PROFILE_PHOTO_CLICKED;
