const APPOINTMENT_END_TIME_RESET = "APPOINTMENT_END_TIME_RESET";

const ACTION_APPOINTMENT_END_TIME_RESET = () => {
  return {
    type: APPOINTMENT_END_TIME_RESET
  };
};

export default ACTION_APPOINTMENT_END_TIME_RESET;
