const ADMIN_REGISTERED_EMPLOYEE_FOUND_RESET =
  "ADMIN_REGISTERED_EMPLOYEE_FOUND_RESET";

const ACTION_ADMIN_REGISTERED_EMPLOYEE_FOUND_RESET = () => {
  return {
    type: ADMIN_REGISTERED_EMPLOYEE_FOUND_RESET,
  };
};

export default ACTION_ADMIN_REGISTERED_EMPLOYEE_FOUND_RESET;
