const DERMAROLLING_NOT_IN_CART = "DERMAROLLING_NOT_IN_CART";

const ACTION_DERMAROLLING_NOT_IN_CART = () => {
  return {
    type: DERMAROLLING_NOT_IN_CART
  };
};

export default ACTION_DERMAROLLING_NOT_IN_CART;
