const ADMIN_LOGIN_PASSWORD_RESET = "ADMIN_LOGIN_PASSWORD_RESET";

const ACTION_ADMIN_LOGIN_PASSWORD_RESET = () => {
  return {
    type: ADMIN_LOGIN_PASSWORD_RESET,
  };
};

export default ACTION_ADMIN_LOGIN_PASSWORD_RESET;
