const ADMIN_APPOINTMENT_TIME_RESET = "ADMIN_APPOINTMENT_TIME_RESET";

const ACTION_ADMIN_APPOINTMENT_TIME_RESET = () => {
  return {
    type: ADMIN_APPOINTMENT_TIME_RESET,
  };
};

export default ACTION_ADMIN_APPOINTMENT_TIME_RESET;
