const CREATE_ACCOUNT_PASSWORD_VALID = "CREATE_ACCOUNT_PASSWORD_VALID";

const ACTION_CREATE_ACCOUNT_PASSWORD_VALID = () => {
  return {
    type: CREATE_ACCOUNT_PASSWORD_VALID
  };
};

export default ACTION_CREATE_ACCOUNT_PASSWORD_VALID;
