const ADMIN_STAFF_MEMBER_EMAIL_RESET = "ADMIN_STAFF_MEMBER_EMAIL_RESET";

const ACTION_ADMIN_STAFF_MEMBER_EMAIL_RESET = () => {
  return {
    type: ADMIN_STAFF_MEMBER_EMAIL_RESET,
  };
};

export default ACTION_ADMIN_STAFF_MEMBER_EMAIL_RESET;
