const CONSENT_FORM_PDF_READY_RESET = "CONSENT_FORM_PDF_READY_RESET";

const ACTION_CONSENT_FORM_PDF_READY_RESET = () => {
  return {
    type: CONSENT_FORM_PDF_READY_RESET,
  };
};

export default ACTION_CONSENT_FORM_PDF_READY_RESET;
