const ADMIN_PERSONAL_EVENT_TITLE_RESET = "ADMIN_PERSONAL_EVENT_TITLE_RESET";

const ACTION_ADMIN_PERSONAL_EVENT_TITLE_RESET = () => {
  return {
    type: ADMIN_PERSONAL_EVENT_TITLE_RESET,
  };
};

export default ACTION_ADMIN_PERSONAL_EVENT_TITLE_RESET;
