const ADMIN_PERSONAL_EVENT_END_TIME_RESET =
  "ADMIN_PERSONAL_EVENT_END_TIME_RESET";

const ACTION_ADMIN_PERSONAL_EVENT_END_TIME_RESET = () => {
  return {
    type: ADMIN_PERSONAL_EVENT_END_TIME_RESET,
  };
};

export default ACTION_ADMIN_PERSONAL_EVENT_END_TIME_RESET;
