const ANYTHING_ELSE_WE_SHOULD_KNOW_NOTES_RESET =
  "ANYTHING_ELSE_WE_SHOULD_KNOW_NOTES_RESET";

const ACTION_ANYTHING_ELSE_WE_SHOULD_KNOW_NOTES_RESET = () => {
  return {
    type: ANYTHING_ELSE_WE_SHOULD_KNOW_NOTES_RESET,
  };
};

export default ACTION_ANYTHING_ELSE_WE_SHOULD_KNOW_NOTES_RESET;
