const ANY_ACCUTANE_NOTES_RESET = "ANY_ACCUTANE_NOTES_RESET";

const ACTION_ANY_ACCUTANE_NOTES_RESET = () => {
  return {
    type: ANY_ACCUTANE_NOTES_RESET
  };
};

export default ACTION_ANY_ACCUTANE_NOTES_RESET;
