const RESET_ALL_EVENING_SERUM_FIELDS = "RESET_ALL_EVENING_SERUM_FIELDS";

const ACTION_RESET_ALL_EVENING_SERUM_FIELDS = () => {
  return {
    type: RESET_ALL_EVENING_SERUM_FIELDS,
  };
};

export default ACTION_RESET_ALL_EVENING_SERUM_FIELDS;
