const CONSENT_FORM_LAST_UPDATED_RESET = "CONSENT_FORM_LAST_UPDATED_RESET";

const ACTION_CONSENT_FORM_LAST_UPDATED_RESET = () => {
  return {
    type: CONSENT_FORM_LAST_UPDATED_RESET,
  };
};

export default ACTION_CONSENT_FORM_LAST_UPDATED_RESET;
