const MICRONEEDLE_TOGGLE_RESET = "MICRONEEDLE_TOGGLE_RESET";

const ACTION_MICRONEEDLE_TOGGLE_RESET = () => {
  return {
    type: MICRONEEDLE_TOGGLE_RESET
  };
};

export default ACTION_MICRONEEDLE_TOGGLE_RESET;
