const ADMIN_CLIENT_PROFILE_SELECTED = "ADMIN_CLIENT_PROFILE_SELECTED";

const ACTION_ADMIN_CLIENT_PROFILE_SELECTED = () => {
  return {
    type: ADMIN_CLIENT_PROFILE_SELECTED,
  };
};

export default ACTION_ADMIN_CLIENT_PROFILE_SELECTED;
