const ADMIN_CLIENT_UPCOMING_APPOINTMENTS_SELECTED =
  "ADMIN_CLIENT_UPCOMING_APPOINTMENTS_SELECTED";

const ACTION_ADMIN_CLIENT_UPCOMING_APPOINTMENTS_SELECTED = () => {
  return {
    type: ADMIN_CLIENT_UPCOMING_APPOINTMENTS_SELECTED,
  };
};

export default ACTION_ADMIN_CLIENT_UPCOMING_APPOINTMENTS_SELECTED;
