const ADMIN_NEW_PASSWORD_NOT_INVALID = "ADMIN_NEW_PASSWORD_NOT_INVALID";

const ACTION_ADMIN_NEW_PASSWORD_NOT_INVALID = () => {
  return {
    type: ADMIN_NEW_PASSWORD_NOT_INVALID,
  };
};

export default ACTION_ADMIN_NEW_PASSWORD_NOT_INVALID;
