const ADMIN_NEW_PASSWORD_INVALID = "ADMIN_NEW_PASSWORD_INVALID";

const ACTION_ADMIN_NEW_PASSWORD_INVALID = () => {
  return {
    type: ADMIN_NEW_PASSWORD_INVALID,
  };
};

export default ACTION_ADMIN_NEW_PASSWORD_INVALID;
