const RESET_ALL_EVENING_MOISTURIZER_FIELDS =
  "RESET_ALL_EVENING_MOISTURIZER_FIELDS";

const ACTION_RESET_ALL_EVENING_MOISTURIZER_FIELDS = () => {
  return {
    type: RESET_ALL_EVENING_MOISTURIZER_FIELDS,
  };
};

export default ACTION_RESET_ALL_EVENING_MOISTURIZER_FIELDS;
