const LOADING_SPINNER_ACTIVE = "LOADING_SPINNER_ACTIVE";

const ACTION_LOADING_SPINNER_ACTIVE = () => {
  return {
    type: LOADING_SPINNER_ACTIVE
  };
};

export default ACTION_LOADING_SPINNER_ACTIVE;
