const NANONEEDLING_TOGGLE_RESET = "NANONEEDLING_TOGGLE_RESET";

const ACTION_NANONEEDLING_TOGGLE_RESET = () => {
  return {
    type: NANONEEDLING_TOGGLE_RESET
  };
};

export default ACTION_NANONEEDLING_TOGGLE_RESET;
