const ADMIN_CONFIRM_NEW_PASSWORD_INVALID = "ADMIN_CONFIRM_NEW_PASSWORD_INVALID";

const ACTION_ADMIN_CONFIRM_NEW_PASSWORD_INVALID = () => {
  return {
    type: ADMIN_CONFIRM_NEW_PASSWORD_INVALID,
  };
};

export default ACTION_ADMIN_CONFIRM_NEW_PASSWORD_INVALID;
