const APPOINTMENT_NOTES_INVALID = "APPOINTMENT_NOTES_INVALID";

const ACTION_APPOINTMENT_NOTES_INVALID = () => {
  return {
    type: APPOINTMENT_NOTES_INVALID
  };
};

export default ACTION_APPOINTMENT_NOTES_INVALID;
