const ADMIN_APPOINTMENT_NOTES_RESET = "ADMIN_APPOINTMENT_NOTES_RESET";

const ACTION_ADMIN_APPOINTMENT_NOTES_RESET = () => {
  return {
    type: ADMIN_APPOINTMENT_NOTES_RESET,
  };
};

export default ACTION_ADMIN_APPOINTMENT_NOTES_RESET;
