const CHEMICAL_PEEL_TOGGLE_RESET = "CHEMICAL_PEEL_TOGGLE_RESET";

const ACTION_CHEMICAL_PEEL_TOGGLE_RESET = () => {
  return {
    type: CHEMICAL_PEEL_TOGGLE_RESET
  };
};

export default ACTION_CHEMICAL_PEEL_TOGGLE_RESET;
