const SURGERY_LAST_3_MONTHS_NO_RESET = "SURGERY_LAST_3_MONTHS_NO_RESET";

const ACTION_SURGERY_LAST_3_MONTHS_NO_RESET = () => {
  return {
    type: SURGERY_LAST_3_MONTHS_NO_RESET
  };
};

export default ACTION_SURGERY_LAST_3_MONTHS_NO_RESET;
