const SURGERY_LAST_3_MONTHS_NO = "SURGERY_LAST_3_MONTHS_NO";

const ACTION_SURGERY_LAST_3_MONTHS_NO = () => {
  return {
    type: SURGERY_LAST_3_MONTHS_NO
  };
};

export default ACTION_SURGERY_LAST_3_MONTHS_NO;
