const REJUVENATE_TOGGLE_RESET = "REJUVENATE_TOGGLE_RESET";

const ACTION_REJUVENATE_TOGGLE_RESET = () => {
  return {
    type: REJUVENATE_TOGGLE_RESET
  };
};

export default ACTION_REJUVENATE_TOGGLE_RESET;
