const ADMIN_NOT_AUTHENTICATED = "ADMIN_NOT_AUTHENTICATED";

const ACTION_ADMIN_NOT_AUTHENTICATED = () => {
  return {
    type: ADMIN_NOT_AUTHENTICATED,
  };
};

export default ACTION_ADMIN_NOT_AUTHENTICATED;
