const ADMIN_SELECTED_TREATMENTS_RESET = "ADMIN_SELECTED_TREATMENTS_RESET";

const ACTION_ADMIN_SELECTED_TREATMENTS_RESET = () => {
  return {
    type: ADMIN_SELECTED_TREATMENTS_RESET,
  };
};

export default ACTION_ADMIN_SELECTED_TREATMENTS_RESET;
