const ULTIMATE_SKIN_CARE_GOALS_NOTES_RESET =
  "ULTIMATE_SKIN_CARE_GOALS_NOTES_RESET";

const ACTION_ULTIMATE_SKIN_CARE_GOALS_NOTES_RESET = () => {
  return {
    type: ULTIMATE_SKIN_CARE_GOALS_NOTES_RESET,
  };
};

export default ACTION_ULTIMATE_SKIN_CARE_GOALS_NOTES_RESET;
