const RESET_ALL_TREATMENT_MASK_FIELDS = "RESET_ALL_TREATMENT_MASK_FIELDS";

const ACTION_RESET_ALL_TREATMENT_MASK_FIELDS = () => {
  return {
    type: RESET_ALL_TREATMENT_MASK_FIELDS,
  };
};

export default ACTION_RESET_ALL_TREATMENT_MASK_FIELDS;
