const MICRODERMABRASION_TOGGLE_RESET = "MICRODERMABRASION_TOGGLE_RESET";

const ACTION_MICRODERMABRASION_TOGGLE_RESET = () => {
  return {
    type: MICRODERMABRASION_TOGGLE_RESET
  };
};

export default ACTION_MICRODERMABRASION_TOGGLE_RESET;
