const PREGNANT_OR_NURSING_NO_RESET = "PREGNANT_OR_NURSING_NO_RESET";

const ACTION_PREGNANT_OR_NURSING_NO_RESET = () => {
  return {
    type: PREGNANT_OR_NURSING_NO_RESET,
  };
};

export default ACTION_PREGNANT_OR_NURSING_NO_RESET;
