const DERMAPLANING_TOGGLE_RESET = "DERMAPLANING_TOGGLE_RESET";

const ACTION_DERMAPLANING_TOGGLE_RESET = () => {
  return {
    type: DERMAPLANING_TOGGLE_RESET
  };
};

export default ACTION_DERMAPLANING_TOGGLE_RESET;
