const ADMIN_PERSONAL_EVENT_DATE_RESET = "ADMIN_PERSONAL_EVENT_DATE_RESET";

const ACTION_ADMIN_PERSONAL_EVENT_DATE_RESET = () => {
  return {
    type: ADMIN_PERSONAL_EVENT_DATE_RESET,
  };
};

export default ACTION_ADMIN_PERSONAL_EVENT_DATE_RESET;
