const SELECT_TIME_NOT_ACTIVE = "SELECT_TIME_NOT_ACTIVE";

const ACTION_SELECT_TIME_NOT_ACTIVE = () => {
  return {
    type: SELECT_TIME_NOT_ACTIVE
  };
};

export default ACTION_SELECT_TIME_NOT_ACTIVE;
