const LIST_ANY_MEDICATIONS_NOTES_RESET = "LIST_ANY_MEDICATIONS_NOTES_RESET";

const ACTION_LIST_ANY_MEDICATIONS_NOTES_RESET = () => {
  return {
    type: LIST_ANY_MEDICATIONS_NOTES_RESET
  };
};

export default ACTION_LIST_ANY_MEDICATIONS_NOTES_RESET;
