const SELECTED_SALT_CAVE_DURATION_RESET = "SELECTED_SALT_CAVE_DURATION_RESET";

const ACTION_SELECTED_SALT_CAVE_DURATION_RESET = () => {
  return {
    type: SELECTED_SALT_CAVE_DURATION_RESET,
  };
};

export default ACTION_SELECTED_SALT_CAVE_DURATION_RESET;
