const USER_NOT_AUTHENTICATED = "USER_NOT_AUTHENTICATED";

const ACTION_USER_NOT_AUTHENTICATED = () => {
  return {
    type: USER_NOT_AUTHENTICATED
  };
};

export default ACTION_USER_NOT_AUTHENTICATED;
