const CANCEL_APPOINTMENT_CLICKED = "CANCEL_APPOINTMENT_CLICKED";

const ACTION_CANCEL_APPOINTMENT_CLICKED = () => {
  return {
    type: CANCEL_APPOINTMENT_CLICKED,
  };
};

export default ACTION_CANCEL_APPOINTMENT_CLICKED;
