const CREATE_ACCOUNT_PHONE_NUMBER_RESET = "CREATE_ACCOUNT_PHONE_NUMBER_RESET";

const ACTION_CREATE_ACCOUNT_PHONE_NUMBER_RESET = () => {
  return {
    type: CREATE_ACCOUNT_PHONE_NUMBER_RESET
  };
};

export default ACTION_CREATE_ACCOUNT_PHONE_NUMBER_RESET;
