const BOOKING_SUMMARY_NOT_ACTIVE = "BOOKING_SUMMARY_NOT_ACTIVE";

const ACTION_BOOKING_SUMMARY_NOT_ACTIVE = () => {
  return {
    type: BOOKING_SUMMARY_NOT_ACTIVE
  };
};

export default ACTION_BOOKING_SUMMARY_NOT_ACTIVE;
