const BOOKING_SUMMARY_ACTIVE = "BOOKING_SUMMARY_ACTIVE";

const ACTION_BOOKING_SUMMARY_ACTIVE = () => {
  return {
    type: BOOKING_SUMMARY_ACTIVE
  };
};

export default ACTION_BOOKING_SUMMARY_ACTIVE;
