const SPLASH_SCREEN_COMPLETE = "SPLASH_SCREEN_COMPLETE";

const ACTION_SPLASH_SCREEN_COMPLETE = () => {
  return {
    type: SPLASH_SCREEN_COMPLETE
  };
};

export default ACTION_SPLASH_SCREEN_COMPLETE;
