const FILLERS_OR_BOTOX_NOTES_RESET = "FILLERS_OR_BOTOX_NOTES_RESET";

const ACTION_FILLERS_OR_BOTOX_NOTES_RESET = () => {
  return {
    type: FILLERS_OR_BOTOX_NOTES_RESET
  };
};

export default ACTION_FILLERS_OR_BOTOX_NOTES_RESET;
