const ANY_FILLERS_OR_BOTOX_NOTES_RESET = "ANY_FILLERS_OR_BOTOX_NOTES_RESET";

const ACTION_ANY_FILLERS_OR_BOTOX_NOTES_RESET = () => {
  return {
    type: ANY_FILLERS_OR_BOTOX_NOTES_RESET
  };
};

export default ACTION_ANY_FILLERS_OR_BOTOX_NOTES_RESET;
