const SURGERY_LAST_3_MONTHS_NOTES_RESET = "SURGERY_LAST_3_MONTHS_NOTES_RESET";

const ACTION_SURGERY_LAST_3_MONTHS_NOTES_RESET = () => {
  return {
    type: SURGERY_LAST_3_MONTHS_NOTES_RESET
  };
};

export default ACTION_SURGERY_LAST_3_MONTHS_NOTES_RESET;
