const ANY_CHEM_PEELS_LAST_MONTH_YES_RESET =
  "ANY_CHEM_PEELS_LAST_MONTH_YES_RESET";

const ACTION_ANY_CHEM_PEELS_LAST_MONTH_YES_RESET = () => {
  return {
    type: ANY_CHEM_PEELS_LAST_MONTH_YES_RESET
  };
};

export default ACTION_ANY_CHEM_PEELS_LAST_MONTH_YES_RESET;
