const FACEBOOK_COMPLETE_REGISTRATION = "FACEBOOK_COMPLETE_REGISTRATION";

const ACTION_FACEBOOK_COMPLETE_REGISTRATION = () => {
  return {
    type: FACEBOOK_COMPLETE_REGISTRATION
  };
};

export default ACTION_FACEBOOK_COMPLETE_REGISTRATION;
