const ADMIN_PERSONAL_EVENT_ALL_DAY = "ADMIN_PERSONAL_EVENT_ALL_DAY";

const ACTION_ADMIN_PERSONAL_EVENT_ALL_DAY = () => {
  return {
    type: ADMIN_PERSONAL_EVENT_ALL_DAY,
  };
};

export default ACTION_ADMIN_PERSONAL_EVENT_ALL_DAY;
