const ADMIN_PERSONAL_EVENT_ALL_DAY_RESET = "ADMIN_PERSONAL_EVENT_ALL_DAY_RESET";

const ACTION_ADMIN_PERSONAL_EVENT_ALL_DAY_RESET = () => {
  return {
    type: ADMIN_PERSONAL_EVENT_ALL_DAY_RESET,
  };
};

export default ACTION_ADMIN_PERSONAL_EVENT_ALL_DAY_RESET;
