const LOGIN_PASSWORD_INVALID = "LOGIN_PASSWORD_INVALID";

const ACTION_LOGIN_PASSWORD_INVALID = () => {
  return {
    type: LOGIN_PASSWORD_INVALID
  };
};

export default ACTION_LOGIN_PASSWORD_INVALID;
