const ADMIN_APPOINTMENT_DATE_RESET = "ADMIN_APPOINTMENT_DATE_RESET";

const ACTION_ADMIN_APPOINTMENT_DATE_RESET = () => {
  return {
    type: ADMIN_APPOINTMENT_DATE_RESET,
  };
};

export default ACTION_ADMIN_APPOINTMENT_DATE_RESET;
