const MICRODERMABRASION_IN_CART = "MICRODERMABRASION_IN_CART";

const ACTION_MICRODERMABRASION_IN_CART = () => {
  return {
    type: MICRODERMABRASION_IN_CART
  };
};

export default ACTION_MICRODERMABRASION_IN_CART;
