const REGISTERED_CLIENT_FOUND = "REGISTERED_CLIENT_FOUND";

const ACTION_REGISTERED_CLIENT_FOUND = () => {
  return {
    type: REGISTERED_CLIENT_FOUND
  };
};

export default ACTION_REGISTERED_CLIENT_FOUND;
