const ADMIN_PERSONAL_EVENT_NOTES_RESET = "ADMIN_PERSONAL_EVENT_NOTES_RESET";

const ACTION_ADMIN_PERSONAL_EVENT_NOTES_RESET = () => {
  return {
    type: ADMIN_PERSONAL_EVENT_NOTES_RESET,
  };
};

export default ACTION_ADMIN_PERSONAL_EVENT_NOTES_RESET;
