const LIST_KNOWN_ALLERGIES_RESET = "LIST_KNOWN_ALLERGIES_RESET";

const ACTION_LIST_KNOWN_ALLERGIES_RESET = () => {
  return {
    type: LIST_KNOWN_ALLERGIES_RESET,
  };
};

export default ACTION_LIST_KNOWN_ALLERGIES_RESET;
