const CONTINUE_BUTTON_ACTIVE = "CONTINUE_BUTTON_ACTIVE";

const ACTION_CONTINUE_BUTTON_ACTIVE = () => {
  return {
    type: CONTINUE_BUTTON_ACTIVE
  };
};

export default ACTION_CONTINUE_BUTTON_ACTIVE;
