const RESET_ALL_SPOT_TREATMENT_FIELDS = "RESET_ALL_SPOT_TREATMENT_FIELDS";

const ACTION_RESET_ALL_SPOT_TREATMENT_FIELDS = () => {
  return {
    type: RESET_ALL_SPOT_TREATMENT_FIELDS,
  };
};

export default ACTION_RESET_ALL_SPOT_TREATMENT_FIELDS;
