const PREGNANT_OR_NURSING_YES_RESET = "PREGNANT_OR_NURSING_YES_RESET";

const ACTION_PREGNANT_OR_NURSING_YES_RESET = () => {
  return {
    type: PREGNANT_OR_NURSING_YES_RESET,
  };
};

export default ACTION_PREGNANT_OR_NURSING_YES_RESET;
