const ADMIN_PERSONAL_EVENT_STAFF = "ADMIN_PERSONAL_EVENT_STAFF";

const ACTION_ADMIN_PERSONAL_EVENT_STAFF = (staff) => {
  return {
    type: ADMIN_PERSONAL_EVENT_STAFF,
    staff,
  };
};

export default ACTION_ADMIN_PERSONAL_EVENT_STAFF;
