const ADMIN_PERSONAL_EVENT_STAFF = "ADMIN_PERSONAL_EVENT_STAFF";

const ACTION_ADMIN_PERSONAL_EVENT_STAFF_RESET = () => {
  return {
    type: ADMIN_PERSONAL_EVENT_STAFF,
  };
};

export default ACTION_ADMIN_PERSONAL_EVENT_STAFF_RESET;
