const ADMIN_STAFF_MEMBER_PHONE_NUMBER_RESET =
  "ADMIN_STAFF_MEMBER_PHONE_NUMBER_RESET";

const ACTION_ADMIN_STAFF_MEMBER_PHONE_NUMBER_RESET = () => {
  return {
    type: ADMIN_STAFF_MEMBER_PHONE_NUMBER_RESET,
  };
};

export default ACTION_ADMIN_STAFF_MEMBER_PHONE_NUMBER_RESET;
