const SKIN_FLAKY_OR_ITCH_NO_RESET = "SKIN_FLAKY_OR_ITCH_NO_RESET";

const ACTION_SKIN_FLAKY_OR_ITCH_NO_RESET = () => {
  return {
    type: SKIN_FLAKY_OR_ITCH_NO_RESET,
  };
};

export default ACTION_SKIN_FLAKY_OR_ITCH_NO_RESET;
