const CREATE_ACCOUNT_FIRST_NAME_RESET = "CREATE_ACCOUNT_FIRST_NAME_RESET";

const ACTION_CREATE_ACCOUNT_FIRST_NAME_RESET = () => {
  return {
    type: CREATE_ACCOUNT_FIRST_NAME_RESET
  };
};

export default ACTION_CREATE_ACCOUNT_FIRST_NAME_RESET;
