const FINAL_BOOK_BUTTON_ACTIVE = "FINAL_BOOK_BUTTON_ACTIVE";

const ACTION_FINAL_BOOK_BUTTON_ACTIVE = () => {
  return {
    type: FINAL_BOOK_BUTTON_ACTIVE
  };
};

export default ACTION_FINAL_BOOK_BUTTON_ACTIVE;
