const SELECTED_ESTHETICIAN_RESET = "SELECTED_ESTHETICIAN_RESET";

const ACTION_SELECTED_ESTHETICIAN_RESET = () => {
  return {
    type: SELECTED_ESTHETICIAN_RESET,
  };
};

export default ACTION_SELECTED_ESTHETICIAN_RESET;
