const ON_ACTIVITY_PAGE_RESET = "ON_ACTIVITY_PAGE_RESET";

const ACTION_ON_ACTIVITY_PAGE_RESET = () => {
  return {
    type: ON_ACTIVITY_PAGE_RESET,
  };
};

export default ACTION_ON_ACTIVITY_PAGE_RESET;
