const ADMIN_PERSONAL_EVENT_BLOCK_TIME = "ADMIN_PERSONAL_EVENT_BLOCK_TIME";

const ACTION_ADMIN_PERSONAL_EVENT_BLOCK_TIME = () => {
  return {
    type: ADMIN_PERSONAL_EVENT_BLOCK_TIME,
  };
};

export default ACTION_ADMIN_PERSONAL_EVENT_BLOCK_TIME;
