const REFORMATTED_DAY_CLONE_RESET = "REFORMATTED_DAY_CLONE_RESET";

const ACTION_REFORMATTED_DAY_CLONE_RESET = () => {
  return {
    type: REFORMATTED_DAY_CLONE_RESET
  };
};

export default ACTION_REFORMATTED_DAY_CLONE_RESET;
