const ANY_HEALTH_PROBLEMS_NOTES_RESET = "ANY_HEALTH_PROBLEMS_NOTES_RESET";

const ACTION_ANY_HEALTH_PROBLEMS_NOTES_RESET = () => {
  return {
    type: ANY_HEALTH_PROBLEMS_NOTES_RESET
  };
};

export default ACTION_ANY_HEALTH_PROBLEMS_NOTES_RESET;
