const ANY_FILLERS_OR_BOTOX_NO_RESET = "ANY_FILLERS_OR_BOTOX_NO_RESET";

const ACTION_ANY_FILLERS_OR_BOTOX_NO_RESET = () => {
  return {
    type: ANY_FILLERS_OR_BOTOX_NO_RESET
  };
};

export default ACTION_ANY_FILLERS_OR_BOTOX_NO_RESET;
