const RESET_ALL_EXFOLIATOR_FIELDS = "RESET_ALL_EXFOLIATOR_FIELDS";

const ACTION_RESET_ALL_EXFOLIATOR_FIELDS = () => {
  return {
    type: RESET_ALL_EXFOLIATOR_FIELDS,
  };
};

export default ACTION_RESET_ALL_EXFOLIATOR_FIELDS;
