const GUEST_CONSENT_FORM_ACCESS_TOKEN_RESET =
  "GUEST_CONSENT_FORM_ACCESS_TOKEN_RESET";

const ACTION_GUEST_CONSENT_FORM_ACCESS_TOKEN_RESET = () => {
  return {
    type: GUEST_CONSENT_FORM_ACCESS_TOKEN_RESET,
  };
};

export default ACTION_GUEST_CONSENT_FORM_ACCESS_TOKEN_RESET;
