const REGISTERED_CLIENT_FOUND_RESET = "REGISTERED_CLIENT_FOUND_RESET";

const ACTION_REGISTERED_CLIENT_FOUND_RESET = () => {
  return {
    type: REGISTERED_CLIENT_FOUND_RESET
  };
};

export default ACTION_REGISTERED_CLIENT_FOUND_RESET;
