const ADMIN_CLIENT_FIRST_NAME_RESET = "ADMIN_CLIENT_FIRST_NAME_RESET";

const ACTION_ADMIN_CLIENT_FIRST_NAME_RESET = () => {
  return {
    type: ADMIN_CLIENT_FIRST_NAME_RESET,
  };
};

export default ACTION_ADMIN_CLIENT_FIRST_NAME_RESET;
