const SQUARE_CUSTOMER_ID_RESET = "SQUARE_CUSTOMER_ID_RESET";

const ACTION_SQUARE_CUSTOMER_ID_RESET = () => {
  return {
    type: SQUARE_CUSTOMER_ID_RESET,
  };
};

export default ACTION_SQUARE_CUSTOMER_ID_RESET;
