const RESET_ALL_EVENING_RX_FIELDS = "RESET_ALL_EVENING_RX_FIELDS";

const ACTION_RESET_ALL_EVENING_RX_FIELDS = () => {
  return {
    type: RESET_ALL_EVENING_RX_FIELDS,
  };
};

export default ACTION_RESET_ALL_EVENING_RX_FIELDS;
