const EXFOLIATING_SCRUBS_RESET = "EXFOLIATING_SCRUBS_RESET";

const ACTION_EXFOLIATING_SCRUBS_RESET = () => {
  return {
    type: EXFOLIATING_SCRUBS_RESET
  };
};

export default ACTION_EXFOLIATING_SCRUBS_RESET;
