const CREATE_ACCOUNT_PHONE_NUMBER_INVALID =
  "CREATE_ACCOUNT_PHONE_NUMBER_INVALID";

const ACTION_CREATE_ACCOUNT_PHONE_NUMBER_INVALID = () => {
  return {
    type: CREATE_ACCOUNT_PHONE_NUMBER_INVALID
  };
};

export default ACTION_CREATE_ACCOUNT_PHONE_NUMBER_INVALID;
