const CREATE_ACCOUNT_EMAIL_RESET = "CREATE_ACCOUNT_EMAIL_RESET";

const ACTION_CREATE_ACCOUNT_EMAIL_RESET = () => {
  return {
    type: CREATE_ACCOUNT_EMAIL_RESET
  };
};

export default ACTION_CREATE_ACCOUNT_EMAIL_RESET;
