const ADMIN_PERSONAL_EVENT_START_TIME = "ADMIN_PERSONAL_EVENT_START_TIME";

const ACTION_ADMIN_PERSONAL_EVENT_START_TIME = (start_time) => {
  return {
    type: ADMIN_PERSONAL_EVENT_START_TIME,
    start_time,
  };
};

export default ACTION_ADMIN_PERSONAL_EVENT_START_TIME;
