const CANCEL_APPOINTMENT_CLICKED_RESET = "CANCEL_APPOINTMENT_CLICKED_RESET";

const ACTION_CANCEL_APPOINTMENT_CLICKED_RESET = () => {
  return {
    type: CANCEL_APPOINTMENT_CLICKED_RESET,
  };
};

export default ACTION_CANCEL_APPOINTMENT_CLICKED_RESET;
