const CREATE_ACCOUNT_EMAIL_INVALID = "CREATE_ACCOUNT_EMAIL_INVALID";

const ACTION_CREATE_ACCOUNT_EMAIL_INVALID = () => {
  return {
    type: CREATE_ACCOUNT_EMAIL_INVALID
  };
};

export default ACTION_CREATE_ACCOUNT_EMAIL_INVALID;
