const MICROCURRENT_TOGGLE_RESET = "MICROCURRENT_TOGGLE_RESET";

const ACTION_MICROCURRENT_TOGGLE_RESET = () => {
  return {
    type: MICROCURRENT_TOGGLE_RESET
  };
};

export default ACTION_MICROCURRENT_TOGGLE_RESET;
