const SURGERY_LAST_3_MONTHS_YES_RESET = "SURGERY_LAST_3_MONTHS_YES_RESET";

const ACTION_SURGERY_LAST_3_MONTHS_YES_RESET = () => {
  return {
    type: SURGERY_LAST_3_MONTHS_YES_RESET
  };
};

export default ACTION_SURGERY_LAST_3_MONTHS_YES_RESET;
