const SURGERY_LAST_3_MONTHS_YES = "SURGERY_LAST_3_MONTHS_YES";

const ACTION_SURGERY_LAST_3_MONTHS_YES = () => {
  return {
    type: SURGERY_LAST_3_MONTHS_YES
  };
};

export default ACTION_SURGERY_LAST_3_MONTHS_YES;
