const CREATE_ACCOUNT_CONFIRM_PASSWORD_INVALID =
  "CREATE_ACCOUNT_CONFIRM_PASSWORD_INVALID";

const ACTION_CREATE_ACCOUNT_CONFIRM_PASSWORD_INVALID = () => {
  return {
    type: CREATE_ACCOUNT_CONFIRM_PASSWORD_INVALID
  };
};

export default ACTION_CREATE_ACCOUNT_CONFIRM_PASSWORD_INVALID;
