const ANY_WAXING_LAST_5_DAYS_YES_RESET = "ANY_WAXING_LAST_5_DAYS_YES_RESET";

const ACTION_ANY_WAXING_LAST_5_DAYS_YES_RESET = () => {
  return {
    type: ANY_WAXING_LAST_5_DAYS_YES_RESET,
  };
};

export default ACTION_ANY_WAXING_LAST_5_DAYS_YES_RESET;
