const ADMIN_CLIENT_PHONE_NUMBER_RESET = "ADMIN_CLIENT_PHONE_NUMBER_RESET";

const ACTION_ADMIN_CLIENT_PHONE_NUMBER_RESET = () => {
  return {
    type: ADMIN_CLIENT_PHONE_NUMBER_RESET,
  };
};

export default ACTION_ADMIN_CLIENT_PHONE_NUMBER_RESET;
