const CONSENT_FORM_ANYTHING_CHANGED = "CONSENT_FORM_ANYTHING_CHANGED";

const ACTION_CONSENT_FORM_ANYTHING_CHANGED = () => {
  return {
    type: CONSENT_FORM_ANYTHING_CHANGED,
  };
};

export default ACTION_CONSENT_FORM_ANYTHING_CHANGED;
