const CONSENT_FORM_ANYTHING_CHANGED_RESET =
  "CONSENT_FORM_ANYTHING_CHANGED_RESET";

const ACTION_CONSENT_FORM_ANYTHING_CHANGED_RESET = () => {
  return {
    type: CONSENT_FORM_ANYTHING_CHANGED_RESET,
  };
};

export default ACTION_CONSENT_FORM_ANYTHING_CHANGED_RESET;
