const DERMAROLLING_TOGGLE_RESET = "DERMAROLLING_TOGGLE_RESET";

const ACTION_DERMAROLLING_TOGGLE_RESET = () => {
  return {
    type: DERMAROLLING_TOGGLE_RESET
  };
};

export default ACTION_DERMAROLLING_TOGGLE_RESET;
