const MICRODERMABRASION_TOGGLE = "MICRODERMABRASION_TOGGLE";

const ACTION_MICRODERMABRASION_TOGGLE = () => {
  return {
    type: MICRODERMABRASION_TOGGLE
  };
};

export default ACTION_MICRODERMABRASION_TOGGLE;
