const LED_THERAPY_TOGGLE_RESET = "LED_THERAPY_TOGGLE_RESET";

const ACTION_LED_THERAPY_TOGGLE_RESET = () => {
  return {
    type: LED_THERAPY_TOGGLE_RESET
  };
};

export default ACTION_LED_THERAPY_TOGGLE_RESET;
