const FILLERS_OR_BOTOX_YES_RESET = "FILLERS_OR_BOTOX_YES_RESET";

const ACTION_FILLERS_OR_BOTOX_YES_RESET = () => {
  return {
    type: FILLERS_OR_BOTOX_YES_RESET
  };
};

export default ACTION_FILLERS_OR_BOTOX_YES_RESET;
