const ANY_FILLERS_OR_BOTOX_YES_RESET = "ANY_FILLERS_OR_BOTOX_YES_RESET";

const ACTION_ANY_FILLERS_OR_BOTOX_YES_RESET = () => {
  return {
    type: ANY_FILLERS_OR_BOTOX_YES_RESET
  };
};

export default ACTION_ANY_FILLERS_OR_BOTOX_YES_RESET;
