const AVAILABILITY_PAGE_OPENED = "AVAILABILITY_PAGE_OPENED";

const ACTION_AVAILABILITY_PAGE_OPENED = () => {
  return {
    type: AVAILABILITY_PAGE_OPENED,
  };
};

export default ACTION_AVAILABILITY_PAGE_OPENED;
