const PAYMENT_INFO_PAGE_OPENED = "PAYMENT_INFO_PAGE_OPENED";

const ACTION_PAYMENT_INFO_PAGE_OPENED = () => {
  return {
    type: PAYMENT_INFO_PAGE_OPENED,
  };
};

export default ACTION_PAYMENT_INFO_PAGE_OPENED;
