const GUEST_CHECKOUT_FORM_PAGE_OPENED = "GUEST_CHECKOUT_FORM_PAGE_OPENED";

const ACTION_GUEST_CHECKOUT_FORM_PAGE_OPENED = () => {
  return {
    type: GUEST_CHECKOUT_FORM_PAGE_OPENED,
  };
};

export default ACTION_GUEST_CHECKOUT_FORM_PAGE_OPENED;
