const ANY_HEALTH_PROBLEMS_YES_RESET = "ANY_HEALTH_PROBLEMS_YES_RESET";

const ACTION_ANY_HEALTH_PROBLEMS_YES_RESET = () => {
  return {
    type: ANY_HEALTH_PROBLEMS_YES_RESET
  };
};

export default ACTION_ANY_HEALTH_PROBLEMS_YES_RESET;
