const CREATE_ACCOUNT_PHONE_NUMBER_VALID = "CREATE_ACCOUNT_PHONE_NUMBER_VALID";

const ACTION_CREATE_ACCOUNT_PHONE_NUMBER_VALID = () => {
  return {
    type: CREATE_ACCOUNT_PHONE_NUMBER_VALID
  };
};

export default ACTION_CREATE_ACCOUNT_PHONE_NUMBER_VALID;
