const CREATE_ACCOUNT_CONFIRM_PASSWORD_RESET =
  "CREATE_ACCOUNT_CONFIRM_PASSWORD_RESET";

const ACTION_CREATE_ACCOUNT_CONFIRM_PASSWORD_RESET = () => {
  return {
    type: CREATE_ACCOUNT_CONFIRM_PASSWORD_RESET
  };
};

export default ACTION_CREATE_ACCOUNT_CONFIRM_PASSWORD_RESET;
