const APPOINTMENT_NOTES_RESET = "APPOINTMENT_NOTES_RESET";

const ACTION_APPOINTMENT_NOTES_RESET = () => {
  return {
    type: APPOINTMENT_NOTES_RESET
  };
};

export default ACTION_APPOINTMENT_NOTES_RESET;
