const APPOINTMENT_NOTES_VALID = "APPOINTMENT_NOTES_VALID";

const ACTION_APPOINTMENT_NOTES_VALID = () => {
  return {
    type: APPOINTMENT_NOTES_VALID
  };
};

export default ACTION_APPOINTMENT_NOTES_VALID;
