const ADMIN_LOGIN_PASSWORD_INVALID = "ADMIN_LOGIN_PASSWORD_INVALID";

const ACTION_ADMIN_LOGIN_PASSWORD_INVALID = () => {
  return {
    type: ADMIN_LOGIN_PASSWORD_INVALID,
  };
};

export default ACTION_ADMIN_LOGIN_PASSWORD_INVALID;
