const RESET_ADMIN_NOTIFICATIONS = "RESET_ADMIN_NOTIFICATIONS";

const ACTION_RESET_ADMIN_NOTIFICATIONS = () => {
  return {
    type: RESET_ADMIN_NOTIFICATIONS,
  };
};

export default ACTION_RESET_ADMIN_NOTIFICATIONS;
