const ADMIN_NEW_PASSWORD_RESET = "ADMIN_NEW_PASSWORD_RESET";

const ACTION_ADMIN_NEW_PASSWORD_RESET = () => {
  return {
    type: ADMIN_NEW_PASSWORD_RESET,
  };
};

export default ACTION_ADMIN_NEW_PASSWORD_RESET;
