const ADMIN_CLIENT_EMAIL_RESET = "ADMIN_CLIENT_EMAIL_RESET";

const ACTION_ADMIN_CLIENT_EMAIL_RESET = () => {
  return {
    type: ADMIN_CLIENT_EMAIL_RESET,
  };
};

export default ACTION_ADMIN_CLIENT_EMAIL_RESET;
