const HYDRO_JELLY_TOGGLE_RESET = "HYDRO_JELLY_TOGGLE_RESET";

const ACTION_HYDRO_JELLY_TOGGLE_RESET = () => {
  return {
    type: HYDRO_JELLY_TOGGLE_RESET
  };
};

export default ACTION_HYDRO_JELLY_TOGGLE_RESET;
