const LOGIN_PASSWORD_NOT_INVALID = "LOGIN_PASSWORD_NOT_INVALID";

const ACTION_LOGIN_PASSWORD_NOT_INVALID = () => {
  return {
    type: LOGIN_PASSWORD_NOT_INVALID
  };
};

export default ACTION_LOGIN_PASSWORD_NOT_INVALID;
