const DIAGNOSED_WITH_ROSACEA_YES_RESET = "DIAGNOSED_WITH_ROSACEA_YES_RESET";

const ACTION_DIAGNOSED_WITH_ROSACEA_YES_RESET = () => {
  return {
    type: DIAGNOSED_WITH_ROSACEA_YES_RESET,
  };
};

export default ACTION_DIAGNOSED_WITH_ROSACEA_YES_RESET;
