const DIAGNOSED_WITH_ROSACEA_YES = "DIAGNOSED_WITH_ROSACEA_YES";

const ACTION_DIAGNOSED_WITH_ROSACEA_YES = () => {
  return {
    type: DIAGNOSED_WITH_ROSACEA_YES,
  };
};

export default ACTION_DIAGNOSED_WITH_ROSACEA_YES;
