const ADMIN_CLIENT_SKIN_CARE_ROUTINE_SELECTED =
  "ADMIN_CLIENT_SKIN_CARE_ROUTINE_SELECTED";

const ACTION_ADMIN_CLIENT_SKIN_CARE_ROUTINE_SELECTED = () => {
  return {
    type: ADMIN_CLIENT_SKIN_CARE_ROUTINE_SELECTED,
  };
};

export default ACTION_ADMIN_CLIENT_SKIN_CARE_ROUTINE_SELECTED;
