const CREATE_ACCOUNT_EMAIL_VALID = "CREATE_ACCOUNT_EMAIL_VALID";

const ACTION_CREATE_ACCOUNT_EMAIL_VALID = () => {
  return {
    type: CREATE_ACCOUNT_EMAIL_VALID
  };
};

export default ACTION_CREATE_ACCOUNT_EMAIL_VALID;
