const LIST_KNOWN_ALLERGIES_NOTES_RESET = "LIST_KNOWN_ALLERGIES_NOTES_RESET";

const ACTION_LIST_KNOWN_ALLERGIES_NOTES_RESET = () => {
  return {
    type: LIST_KNOWN_ALLERGIES_NOTES_RESET,
  };
};

export default ACTION_LIST_KNOWN_ALLERGIES_NOTES_RESET;
