const ADMIN_APPOINTMENT_DURATION_RESET = "ADMIN_APPOINTMENT_DURATION_RESET";

const ACTION_ADMIN_APPOINTMENT_DURATION_RESET = () => {
  return {
    type: ADMIN_APPOINTMENT_DURATION_RESET,
  };
};

export default ACTION_ADMIN_APPOINTMENT_DURATION_RESET;
