const ADMIN_LOGIN_EMAIL_INVALID = "ADMIN_LOGIN_EMAIL_INVALID";

const ACTION_ADMIN_LOGIN_EMAIL_INVALID = () => {
  return {
    type: ADMIN_LOGIN_EMAIL_INVALID,
  };
};

export default ACTION_ADMIN_LOGIN_EMAIL_INVALID;
