const ADMIN_LOGIN_EMAIL_NOT_INVALID = "ADMIN_LOGIN_EMAIL_NOT_INVALID";

const ACTION_ADMIN_LOGIN_EMAIL_NOT_INVALID = () => {
  return {
    type: ADMIN_LOGIN_EMAIL_NOT_INVALID,
  };
};

export default ACTION_ADMIN_LOGIN_EMAIL_NOT_INVALID;
