const RESET_ALL_MORNING_CLEANSER_FIELDS = "RESET_ALL_MORNING_CLEANSER_FIELDS";

const ACTION_RESET_ALL_MORNING_CLEANSER_FIELDS = () => {
  return {
    type: RESET_ALL_MORNING_CLEANSER_FIELDS,
  };
};

export default ACTION_RESET_ALL_MORNING_CLEANSER_FIELDS;
