const JET_HYDRO_PEEL_TOGGLE_RESET = "JET_HYDRO_PEEL_TOGGLE_RESET";

const ACTION_JET_HYDRO_PEEL_TOGGLE_RESET = () => {
  return {
    type: JET_HYDRO_PEEL_TOGGLE_RESET,
  };
};

export default ACTION_JET_HYDRO_PEEL_TOGGLE_RESET;
