const DIAGNOSED_WITH_ROSACEA_NO = "DIAGNOSED_WITH_ROSACEA_NO";

const ACTION_DIAGNOSED_WITH_ROSACEA_NO = () => {
  return {
    type: DIAGNOSED_WITH_ROSACEA_NO,
  };
};

export default ACTION_DIAGNOSED_WITH_ROSACEA_NO;
