const DIAGNOSED_WITH_ROSACEA_NO_RESET = "DIAGNOSED_WITH_ROSACEA_NO_RESET";

const ACTION_DIAGNOSED_WITH_ROSACEA_NO_RESET = () => {
  return {
    type: DIAGNOSED_WITH_ROSACEA_NO_RESET,
  };
};

export default ACTION_DIAGNOSED_WITH_ROSACEA_NO_RESET;
