const ANY_CHEM_PEELS_LAST_MONTH_NO = "ANY_CHEM_PEELS_LAST_MONTH_NO";

const ACTION_ANY_CHEM_PEELS_LAST_MONTH_NO = () => {
  return {
    type: ANY_CHEM_PEELS_LAST_MONTH_NO
  };
};

export default ACTION_ANY_CHEM_PEELS_LAST_MONTH_NO;
