const CREATE_ACCOUNT_PHONE_NUMBER_NOT_INVALID =
  "CREATE_ACCOUNT_PHONE_NUMBER_NOT_INVALID";

const ACTION_CREATE_ACCOUNT_PHONE_NUMBER_NOT_INVALID = () => {
  return {
    type: CREATE_ACCOUNT_PHONE_NUMBER_NOT_INVALID
  };
};

export default ACTION_CREATE_ACCOUNT_PHONE_NUMBER_NOT_INVALID;
