const ADMIN_STAFF_MEMBER_LAST_NAME_RESET = "ADMIN_STAFF_MEMBER_LAST_NAME_RESET";

const ACTION_ADMIN_STAFF_MEMBER_LAST_NAME_RESET = () => {
  return {
    type: ADMIN_STAFF_MEMBER_LAST_NAME_RESET,
  };
};

export default ACTION_ADMIN_STAFF_MEMBER_LAST_NAME_RESET;
