const RESET_ALL_EVENING_EYE_CREAM_FIELDS = "RESET_ALL_EVENING_EYE_CREAM_FIELDS";

const ACTION_RESET_ALL_EVENING_EYE_CREAM_FIELDS = () => {
  return {
    type: RESET_ALL_EVENING_EYE_CREAM_FIELDS,
  };
};

export default ACTION_RESET_ALL_EVENING_EYE_CREAM_FIELDS;
