const SKIN_FLAKY_OR_ITCH_YES_RESET = "SKIN_FLAKY_OR_ITCH_YES_RESET";

const ACTION_SKIN_FLAKY_OR_ITCH_YES_RESET = () => {
  return {
    type: SKIN_FLAKY_OR_ITCH_YES_RESET,
  };
};

export default ACTION_SKIN_FLAKY_OR_ITCH_YES_RESET;
