const EXTRA_EXTRACTIONS_TOGGLE_RESET = "EXTRA_EXTRACTIONS_TOGGLE_RESET";

const ACTION_EXTRA_EXTRACTIONS_TOGGLE_RESET = () => {
  return {
    type: EXTRA_EXTRACTIONS_TOGGLE_RESET
  };
};

export default ACTION_EXTRA_EXTRACTIONS_TOGGLE_RESET;
