const RESET_ALL_MORNING_TONER_FIELDS = "RESET_ALL_MORNING_TONER_FIELDS";

const ACTION_RESET_ALL_MORNING_TONER_FIELDS = () => {
  return {
    type: RESET_ALL_MORNING_TONER_FIELDS,
  };
};

export default ACTION_RESET_ALL_MORNING_TONER_FIELDS;
