const ADMIN_DUMMY_TEMPORARY_TOKEN_RESET = "ADMIN_DUMMY_TEMPORARY_TOKEN_RESET";

const ACTION_ADMIN_DUMMY_TEMPORARY_TOKEN_RESET = () => {
  return {
    type: ADMIN_DUMMY_TEMPORARY_TOKEN_RESET,
  };
};

export default ACTION_ADMIN_DUMMY_TEMPORARY_TOKEN_RESET;
