const ADMIN_NEW_PASSWORD_NOT_VALID = "ADMIN_NEW_PASSWORD_NOT_VALID";

const ACTION_ADMIN_NEW_PASSWORD_NOT_VALID = () => {
  return {
    type: ADMIN_NEW_PASSWORD_NOT_VALID,
  };
};

export default ACTION_ADMIN_NEW_PASSWORD_NOT_VALID;
