const ADMIN_APPOINTMENT_STAFF_MEMBER_RESET =
  "ADMIN_APPOINTMENT_STAFF_MEMBER_RESET";

const ACTION_ADMIN_APPOINTMENT_STAFF_MEMBER_RESET = () => {
  return {
    type: ADMIN_APPOINTMENT_STAFF_MEMBER_RESET,
  };
};

export default ACTION_ADMIN_APPOINTMENT_STAFF_MEMBER_RESET;
