const ADMIN_STAFF_MEMBER_ROLES_RESET = "ADMIN_STAFF_MEMBER_ROLES_RESET";

const ACTION_ADMIN_STAFF_MEMBER_ROLES_RESET = () => {
  return {
    type: ADMIN_STAFF_MEMBER_ROLES_RESET,
  };
};

export default ACTION_ADMIN_STAFF_MEMBER_ROLES_RESET;
