const EXTRA_EXTRACTIONS_TOGGLE = "EXTRA_EXTRACTIONS_TOGGLE";

const ACTION_EXTRA_EXTRACTIONS_TOGGLE = () => {
  return {
    type: EXTRA_EXTRACTIONS_TOGGLE
  };
};

export default ACTION_EXTRA_EXTRACTIONS_TOGGLE;
