const ADMIN_CONFIRM_NEW_PASSWORD_NOT_VALID =
  "ADMIN_CONFIRM_NEW_PASSWORD_NOT_VALID";

const ACTION_ADMIN_CONFIRM_NEW_PASSWORD_NOT_VALID = () => {
  return {
    type: ADMIN_CONFIRM_NEW_PASSWORD_NOT_VALID,
  };
};

export default ACTION_ADMIN_CONFIRM_NEW_PASSWORD_NOT_VALID;
