const ADMIN_CONFIRM_NEW_PASSWORD_VALID = "ADMIN_CONFIRM_NEW_PASSWORD_VALID";

const ACTION_ADMIN_CONFIRM_NEW_PASSWORD_VALID = () => {
  return {
    type: ADMIN_CONFIRM_NEW_PASSWORD_VALID,
  };
};

export default ACTION_ADMIN_CONFIRM_NEW_PASSWORD_VALID;
