const ADMIN_REGISTERED_EMPLOYEE_FOUND = "ADMIN_REGISTERED_EMPLOYEE_FOUND";

const ACTION_ADMIN_REGISTERED_EMPLOYEE_FOUND = () => {
  return {
    type: ADMIN_REGISTERED_EMPLOYEE_FOUND,
  };
};

export default ACTION_ADMIN_REGISTERED_EMPLOYEE_FOUND;
