const ADMIN_CONFIRM_NEW_PASSWORD_NOT_INVALID =
  "ADMIN_CONFIRM_NEW_PASSWORD_NOT_INVALID";

const ACTION_ADMIN_CONFIRM_NEW_PASSWORD_NOT_INVALID = () => {
  return {
    type: ADMIN_CONFIRM_NEW_PASSWORD_NOT_INVALID,
  };
};

export default ACTION_ADMIN_CONFIRM_NEW_PASSWORD_NOT_INVALID;
