const ANY_CHEM_PEELS_LAST_MONTH_YES = "ANY_CHEM_PEELS_LAST_MONTH_YES";

const ACTION_ANY_CHEM_PEELS_LAST_MONTH_YES = () => {
  return {
    type: ANY_CHEM_PEELS_LAST_MONTH_YES
  };
};

export default ACTION_ANY_CHEM_PEELS_LAST_MONTH_YES;
