const CREATE_ACCOUNT_PHONE_NUMBER_NOT_VALID =
  "CREATE_ACCOUNT_PHONE_NUMBER_NOT_VALID";

const ACTION_CREATE_ACCOUNT_PHONE_NUMBER_NOT_VALID = () => {
  return {
    type: CREATE_ACCOUNT_PHONE_NUMBER_NOT_VALID
  };
};

export default ACTION_CREATE_ACCOUNT_PHONE_NUMBER_NOT_VALID;
