const ADMIN_NEW_PASSWORD_VALID = "ADMIN_NEW_PASSWORD_VALID";

const ACTION_ADMIN_NEW_PASSWORD_VALID = () => {
  return {
    type: ADMIN_NEW_PASSWORD_VALID,
  };
};

export default ACTION_ADMIN_NEW_PASSWORD_VALID;
