const FINAL_BOOKING_MODAL_ACTIVE = "FINAL_BOOKING_MODAL_ACTIVE";

const ACTION_FINAL_BOOKING_MODAL_ACTIVE = () => {
  return {
    type: FINAL_BOOKING_MODAL_ACTIVE,
  };
};

export default ACTION_FINAL_BOOKING_MODAL_ACTIVE;
