const FINAL_BOOKING_MODAL_RESET = "FINAL_BOOKING_MODAL_RESET";

const ACTION_FINAL_BOOKING_MODAL_RESET = () => {
  return {
    type: FINAL_BOOKING_MODAL_RESET,
  };
};

export default ACTION_FINAL_BOOKING_MODAL_RESET;
