const ANY_WAXING_LAST_5_DAYS_NO = "ANY_WAXING_LAST_5_DAYS_NO";

const ACTION_ANY_WAXING_LAST_5_DAYS_NO = () => {
  return {
    type: ANY_WAXING_LAST_5_DAYS_NO
  };
};

export default ACTION_ANY_WAXING_LAST_5_DAYS_NO;
