const ANY_WAXING_LAST_5_DAYS_NO_RESET = "ANY_WAXING_LAST_5_DAYS_NO_RESET";

const ACTION_ANY_WAXING_LAST_5_DAYS_NO_RESET = () => {
  return {
    type: ANY_WAXING_LAST_5_DAYS_NO_RESET
  };
};

export default ACTION_ANY_WAXING_LAST_5_DAYS_NO_RESET;
